language: node_js
node_js:
    - "lts/*"

cache:
    directories:
      - "node_modules"

stages:
    - lint
    - test

before_install:
    - npm config set '//npm.pkg.github.com/:_authToken' "${GPR_TOK}"
    - npm ci

jobs:
    include:
      - stage: lint
        name: "Lint codebase"
        script:
          - npm run lint
      - stage: test
        name: "Unit and coverage tests"
        script:
          - npm run test:setup
          - npm run test
          - npm run coverage

notifications:
    email:
      - sdnziaka@gmail.com
